<%
'response.Write("hellowwwwwwwwwwwwwwww"&arrAcademic(13, i))

    If arrAcademic(13, i) = "1" Then
		ssc_hsc_dist_name = "Brahmanbaria"
	ElseIf arrAcademic(13, i) = "2" Then
		ssc_hsc_dist_name = "Bagerhat"
	ElseIf arrAcademic(13, i) = "3" Then
		ssc_hsc_dist_name = "Bandarban"
	ElseIf arrAcademic(13, i) = "4" Then
		ssc_hsc_dist_name = "Barishal"
	ElseIf arrAcademic(13, i) = "5" Then
		ssc_hsc_dist_name = "Bhola"
	ElseIf arrAcademic(13, i) = "6" Then
		ssc_hsc_dist_name = "Bogura"
	ElseIf arrAcademic(13, i) = "7" Then
		ssc_hsc_dist_name = "Borguna"
	ElseIf arrAcademic(13, i) = "8" Then
		ssc_hsc_dist_name = "Chandpur"
	ElseIf arrAcademic(13, i) = "9" Then
		ssc_hsc_dist_name = "Chapainawabganj"
	ElseIf arrAcademic(13, i) = "10" Then
		ssc_hsc_dist_name = "Chattogram"
	ElseIf arrAcademic(13, i) = "11" Then
		ssc_hsc_dist_name = "Chuadanga"
	ElseIf arrAcademic(13, i) = "12" Then
		ssc_hsc_dist_name = "Cumilla"
	ElseIf arrAcademic(13, i) = "13" Then
		ssc_hsc_dist_name = "Cox's Bazar"
	ElseIf arrAcademic(13, i) = "14" Then
		ssc_hsc_dist_name = "Dhaka"
	ElseIf arrAcademic(13, i) = "15" Then
		ssc_hsc_dist_name = "Dinajpur"
	ElseIf arrAcademic(13, i) = "16" Then
		ssc_hsc_dist_name = "Faridpur"
	ElseIf arrAcademic(13, i) = "17" Then
		ssc_hsc_dist_name = "Feni"
	ElseIf arrAcademic(13, i) = "18" Then
		ssc_hsc_dist_name = "Gaibandha"
	ElseIf arrAcademic(13, i) = "19" Then
		ssc_hsc_dist_name = "Gazipur"
	ElseIf arrAcademic(13, i) = "20" Then
		ssc_hsc_dist_name = "Gopalgonj"
	ElseIf arrAcademic(13, i) = "21" Then
		ssc_hsc_dist_name = "Hobigonj"
	ElseIf arrAcademic(13, i) = "22" Then
		ssc_hsc_dist_name = "Jamalpur"
	ElseIf arrAcademic(13, i) = "23" Then
		ssc_hsc_dist_name = "Jashore"
	ElseIf arrAcademic(13, i) = "24" Then
		ssc_hsc_dist_name = "Jhalokathi"
	ElseIf arrAcademic(13, i) = "25" Then
		ssc_hsc_dist_name = "Jhenaidah"
	ElseIf arrAcademic(13, i) = "26" Then
		ssc_hsc_dist_name = "Joypurhat"
	ElseIf arrAcademic(13, i) = "27" Then
		ssc_hsc_dist_name = "Khagrachari"
	ElseIf arrAcademic(13, i) = "28" Then
		ssc_hsc_dist_name = "Khulna"
	ElseIf arrAcademic(13, i) = "29" Then
		ssc_hsc_dist_name = "Kishorgonj"
	ElseIf arrAcademic(13, i) = "30" Then
		ssc_hsc_dist_name = "Kurigram"
	ElseIf arrAcademic(13, i) = "31" Then
		ssc_hsc_dist_name = "Kushtia"
	ElseIf arrAcademic(13, i) = "32" Then
		ssc_hsc_dist_name = "Lalmonirhat"
	ElseIf arrAcademic(13, i) = "33" Then
		ssc_hsc_dist_name = "Laxmipur"
	ElseIf arrAcademic(13, i) = "34" Then
		ssc_hsc_dist_name = "Madaripur"
	ElseIf arrAcademic(13, i) = "35" Then
		ssc_hsc_dist_name = "Magura"
	ElseIf arrAcademic(13, i) = "36" Then
		ssc_hsc_dist_name = "Manikgonj"
	ElseIf arrAcademic(13, i) = "37" Then
		ssc_hsc_dist_name = "Meherpur"
	ElseIf arrAcademic(13, i) = "38" Then
		ssc_hsc_dist_name = "MoulaviBazar"
	ElseIf arrAcademic(13, i) = "39" Then
		ssc_hsc_dist_name = "Munshigonj"
	ElseIf arrAcademic(13, i) = "40" Then
		ssc_hsc_dist_name = "Mymensingh"
	ElseIf arrAcademic(13, i) = "41" Then
		ssc_hsc_dist_name = "Naogaon"
	ElseIf arrAcademic(13, i) = "42" Then
		ssc_hsc_dist_name = "Narail"
	ElseIf arrAcademic(13, i) = "43" Then
		ssc_hsc_dist_name = "Narayangonj"
	ElseIf arrAcademic(13, i) = "44" Then
		ssc_hsc_dist_name = "Narshingdi"
	ElseIf arrAcademic(13, i) = "45" Then
		ssc_hsc_dist_name = "Natore"
	ElseIf arrAcademic(13, i) = "46" Then
		ssc_hsc_dist_name = "Netrokona"
	ElseIf arrAcademic(13, i) = "47" Then
		ssc_hsc_dist_name = "Nilphamari"
	ElseIf arrAcademic(13, i) = "48" Then
		ssc_hsc_dist_name = "Noakhali"
	ElseIf arrAcademic(13, i) = "49" Then
		ssc_hsc_dist_name = "Pabna"
	ElseIf arrAcademic(13, i) = "50" Then
		ssc_hsc_dist_name = "Panchagahr"
	ElseIf arrAcademic(13, i) = "51" Then
		ssc_hsc_dist_name = "Patuakhali"
	ElseIf arrAcademic(13, i) = "52" Then
		ssc_hsc_dist_name = "Pirojpur"
	ElseIf arrAcademic(13, i) = "53" Then
		ssc_hsc_dist_name = "Rajbari"
	ElseIf arrAcademic(13, i) = "54" Then
		ssc_hsc_dist_name = "Rajshahi"
	ElseIf arrAcademic(13, i) = "55" Then
		ssc_hsc_dist_name = "Rangamati"
	ElseIf arrAcademic(13, i) = "56" Then
		ssc_hsc_dist_name = "Rangpur"
	ElseIf arrAcademic(13, i) = "57" Then
		ssc_hsc_dist_name = "Satkhira"
	ElseIf arrAcademic(13, i) = "58" Then
		ssc_hsc_dist_name = "Shariatpur"
	ElseIf arrAcademic(13, i) = "59" Then
		ssc_hsc_dist_name = "Sherpur"
	ElseIf arrAcademic(13, i) = "60" Then
		ssc_hsc_dist_name = "Sirajgonj"
	ElseIf arrAcademic(13, i) = "61" Then
		ssc_hsc_dist_name = "Sunamgonj"
	ElseIf arrAcademic(13, i) = "62" Then
		ssc_hsc_dist_name = "Sylhet"
	ElseIf arrAcademic(13, i) = "63" Then
		ssc_hsc_dist_name = "Tangail"
	ElseIf arrAcademic(13, i) = "64" Then
		ssc_hsc_dist_name = "Thakurgaon"
	End If

%>
