<%	

str = ""
str = str & "  <div class='c-wrapper'> "
    
str = str & "     	<table class='logo'>"
str = str & "           <tr> "
 str = str & "            <td class='t-a-r'> "
 str = str & "            	<div class='logo-wrapper'> "
  str = str & strEmc
  str = str & "               </div> "
 str = str & "            </td> "
 str = str & "          </tr> "
 str = str & "        </table> "
        
 str = str & "        <table class='top'> "
 str = str & "          <tr> "
 str = str & "            <td colspan='2'>"&strDate&"</td> "
  str = str & "         </tr> "
  str = str & "         <tr> "
    str = str & "         <td class='w-six-p'> "
    str = str & "         	<div class='title'><strong>"&strGenderName&"&nbsp;" & strName &"</strong></div> "
    str = str & "             <div class='title'>" & strContactAddress &" </div> "
    str = str & "         </td> "
     str = str & "        <td class='w-for-p'> "
     str = str & "        	<table class='top-inner'> "
     str = str & "              <tr> "
      str = str & "               <td class='w-for-p'><strong>Roll No.</strong></td> "
      str = str & "               <td class='w-six-p'>&nbsp;"&intRoll&"&nbsp; </td> "
       str = str & "            </tr> "
       'str = str & "            <tr> "
       ' str = str & "             <td class='w-for-p'><strong>Tracking No.</strong></td> "
       ' str = str & "             <td class='w-six-p'>&nbsp;"&varTN&"&nbsp;</td> "
       'str = str & "            </tr> "
        str = str & "         </table> "
        str = str & "     </td> "
       str = str & "    </tr> "
      str = str & "   </table> "
        
     str = str & "    <table class='cont'> "
     str = str & "      <tr> "
      str = str & "       <td class='w-eig-p'> "
         str = str & "    	<div class='title'>Dear Applicant:</div> <br>"
         str = str & "        <div class='title'><strong><p>REFERENCE: JOB VACANCY ADVERTISEMENT IN BDJOBS.COM ON SEPTEMBER 20, 2018</p></strong><br></div> "
            str = str & "     <div class='title'><p><strong>EMPLOYER: A LEADING PRIVATE COMMERCIAL BANK </strong></p></div> "
          str = str & "   </td> "
         str = str & "    <td class='w-twe-p' align='right'> "
          str = str & "   	<div class='img-wrapper'>" & varImg & "</div> "
         str = str & "    </td> "
        str = str & "   </tr> "
        str = str & "   <tr> "
          str = str & "   <td colspan='2'> "
            str = str & " <br><br>	<div class='title'><p><strong>ADMIT CARD: WRITTEN TEST FOR THE RECRUITMENT OF "&strShortNamePost&" OFFICER (ON PROBATION)</strong><br><br></p></div> "
          str = str & "   </td> "
       str = str & "    </tr> "
        str = str & "   <tr> "
          str = str & "   <td colspan='2'> "
            str = str & " 	<div class='title'> "
                str = str & " 	<p>Thank you for your interest to build a career in the banking sector.</p> "
                   str = str & "  <p><br>Congratulations! You have been shortlisted for the competitive written test, as part of the selection process. E-Zone will hold the written examination on behalf of private commercial bank. Examination details are furnished below:<br><br></p> "
                  ' str = str & "  <p><br>E‐Zone will hold the written examination on behalf of Prime Bank Limited.</p> "
                 ' str = str & "   <p><br>Examination details are furnished below:<br></p> "
               str = str & "  </div> "
           str = str & "  </td> "
         str = str & "  </tr> "
      str = str & "   </table> "
        
   str = str & "    <table class='bottom-t'> "
      str = str & "     <tr> "
      str = str & "       <td class='w-thir-f-p'> "
       str = str & "      	<div class='title'><strong>Written Test Day & Date</strong></div>"
      str = str & "       </td> "
      str = str & "       <td class='w-fiv-p t-a-c'> "
          str = str & "   	<div class='title'><strong>:</strong></div> "
          str = str & "   </td> "
         str = str & "    <td class='w-six-p'> "
            str = str & " 	<div class='title'><strong>Friday, October 05, 2018</strong></div>"
          str = str & "   </td>"
        str = str & "   </tr>"
        str = str & "   <tr>"
           str = str & "  <td class='w-thir-f-p'>"
            str = str & " 	<div class='title'><strong>Reporting time</strong></div>"
          str = str & "   </td>"
          str = str & "   <td class='w-fiv-p t-a-c'>"
            	str = str & " <div class='title'><strong>:</strong></div>"
          str = str & "   </td>" 
          str = str & "   <td class='w-six-p'>" 
            	str = str & " <div class='title'><strong>08:30 am (you must be seated by 08:45 am)</strong></div> "
           str = str & "  </td> "
         str = str & "  </tr> "
        str = str & "   <tr> "
          str = str & "   <td class='w-thir-f-p'> "
            str = str & " 	<div class='title'><strong>Examination time</strong></div> "
          str = str & "   </td> "
          str = str & "   <td class='w-fiv-p t-a-c'> "
          str = str & "   	<div class='title'><strong>:</strong></div> "
          str = str & "   </td> "
        str = str & "     <td class='w-six-p'> "
            str = str & " 	<div class='title'><strong>From 9:00 am to 11:00 am</strong></div>"
         str = str & "    </td>"
        str = str & "   </tr>"
        str = str & "   <tr>"
        str = str & "     <td class='w-thir-f-p'>"
        str = str & "     	<div class='title'><strong>Venue</strong></div>"
        str = str & "     </td>"
       str = str & "      <td class='w-fiv-p t-a-c'>"
          str = str & "   	<div class='title'><strong>:</strong></div>"
         str = str & "    </td>"
         str = str & "    <td class='w-six-p'>"
           str = str & "  	<div class='title'><strong>Ideal College, 65, Central Road, Dhanmondi, Dhaka 1205</strong></div>"
          str = str & "   </td>"
       str = str & "    </tr>"
     str = str & "    </table>"
        
        
    str = str & "     <table class='bottom-b'>"
      str = str & "     <tr>"
        str = str & "     <th colspan='2'>"
            	str = str & " <h4><strong>INSTRUCTIONS TO THE CANDIDATES TO BE ABLE TO SIT FOR THE EXAMINATION</strong></h4>"
          str = str & "   </th>"
        str = str & "   </tr>"
       str = str & "    <tr>"
       str = str & "      <td valign='top'>"
         str = str & "    	"
               str = str & "  	<p>1. Bring this admit card (original).</p>"
                 str = str & "    <p>2.	Bring one additional identification like your ‐ National ID (original) or Passport .(Original) or car driving license (Original).</p>"
                 str = str & "    <p>3.	Bring only black ball point pen(s) to write your answers.</p>"
                 str = str & "    <p>4.	The examination would be held in English.</p>"
                 str = str & "    <p>5.	Use of any type of calculating device is not permissible; do not bring any with you.</p> "
              str = str & "    "
           str = str & "  </td> "
         str = str & "    <td> "
            str = str & " 	"
                str = str & " 	<p>6.	Mobile phone or any mobile device is not allowed inside the examination hall; do not bring any with you.</p> "
                  str = str & "   <p>7.	Questions are to be answered on the script supplied; do not bring additional papers.</p> "
                  str = str & "   <p>8.	This is a competitive examination. Therefore, all must follow instructions.</p> "
                  str = str & "   <p>9.	Ethical behavior is expected from the examinee, at all times.</p> "
                 'str = str & "    <p>This is a competitive examination. Therefore, all must follow instructions.</p> "
             ' str = str & "       <p>Ethical behavior is expected from the examinee, at all times.</p> "
            str = str & "  "
         str = str & "    </td> "
         str = str & "  </tr> "
      str = str & "   </table> "
        
      str = str & "   <table class='cont'> "
        str = str & "    <tr>"
          str = str & "     <td> "
             str = str & "    <p><br>We look forward to seeing you on the date, reporting time and venue mentioned above.</p> "
             str = str & "    <p><br>Sincerely yours, <br />For & on behalf of E‐Zone HRM Limited</p> "
             str = str & "    <div class='i-wrapper'> "
              str = str & varImgT 
              str = str & "       <div><p>Authorized Signature<br><br><br><br></p></div>"
            str = str & "     </div>"
         str = str & "    </td>"
       str = str & "    </tr>"
     str = str & "    </table>"
        
      str = str & "   <table class='bottom-t'>"
      str = str & "     <tr>"
         str = str & "    <td class='t-a-c'>"
            str = str & " 	<strong>Please safe keep this admit card for further selection process, if you qualify</strong>"
          str = str & "   </td>"
     str = str & "      </tr>"
      str = str & "   </table>"
        
       str = str & "  <table class='top'>"
         str = str & "  <tr> "
        str = str & "     <td align='center'><p><br><br><br><br><br><br><br><br> <strong style='font-size:9px;'>E-Zone HRM Limited, Planners Tower (10th Floor), 13/A Bir Uttam C.R. Dutta Road (Sonargaon Road), Dhaka – 1000, Bangladesh<br> Phones: (880-2)-9614900, 9674679, Cell: 01714013100, 01779896986, <a href='mailto:impulsealamin@yahoo.com'>e-mail: info@e-zonebd.com,</a> <a href='#'>web: www.e-zonebd.com</a></strong></p> </td> "
       str = str & "    </tr> "
     str = str & "    </table> "

str = str & " 	</div> "


'response.Write(str) 


%>