<%
str = ""
str = " <div class='c-wrapper' style='font-size:14px;'> " 
str = str & " <table class='logo'> " 
str = str & "   <tr>  "
str = str & "      <td class='t-a-r' align='center'> "
str = str & "        <div class='logo-wrapper' align='center' > "
str = str & " <img src='http://ers.bdjobs.com/applications/shahjalalbank/dev/images/logo.png'/>"
str = str & "       </div> "
str = str & "     </td> "
str = str & "  </tr>"
str = str & " </table> "

str = str & " <table class='cont' style='font-size:14px;'> "

str = str & "    <tr> "
str = str & "      <td colspan='2' align='center'> "
str = str & "        <div class='title'> "
str = str & "              <strong>Human Resources Division</strong> "
str = str & "         </div>"
str = str & "      </td>"
str = str & "    </tr>"

str = str & "    <tr> "
str = str & "      <td colspan='2'> "
str = str & "         <div class='title'>November 18, 2018</div> "
str = str & "      </td>"
str = str & "    </tr>"

str = str & "    <tr> "
str = str & "      <td colspan='2' align='center' > "
str = str & "         <div class='title' style='font-size:20px;'><strong><u>Admit Card</u></strong></div> "
str = str & "      </td>"
str = str & "    </tr>"


str = str & "   <tr>"
str = str & " <td class='w-sev-four-p'> "
str = str & "   <table class='top-l'>"
str = str & "      <tr> "
str = str & "        <td class='w-thir-f-p'>"
str = str & "           <div class='title'>"
str = str & "        <strong>Roll No.</strong>"
str = str & "          </div>"
str = str & "        </td>"
str = str & "        <td class='w-fiv-p t-a-c'> "
str = str & "        <div class='title'>"
str = str & "       <strong>:</strong>"
str = str & "        </div>"
str = str & "         </td>"
str = str & "    <td class='w-six-p'>"
str = str & "     <div class='title'> "
str = str & "     <strong>"&intRoll&"</strong>"
str = str & "     </div>"
str = str & "    </td>"
str = str & "   </tr>"

str = str & "   <tr>"
str = str & "    <td class='w-thir-f-p'> "
str = str & "     <div class='title'>"
str = str & "       <strong>Job Reference No.</strong>"
str = str & "     </div>"
str = str & "    </td>"
str = str & "    <td class='w-fiv-p t-a-c'>"
str = str & "    <div class='title'><strong>:</strong></div>"
str = str & "    </td>"
str = str & "    <td class='w-six-p'> <div class='title'><strong>"&varTN&" </strong></div></td>"
str = str & "    </tr>"
str = str & "     <tr>"
str = str & "       <td class='w-thir-f-p'>"
str = str & "         <div class='title'><strong>Name</strong></div>"
str = str & "      </td>"
str = str & "     <td class='w-fiv-p t-a-c'> "
str = str & "       <div class='title'><strong>:</strong></div>"
str = str & "      </td>"
str = str & "     <td class='w-six-p'>"
str = str & "     <div class='title'><strong>"&strGenderName&" "&strName &"</strong></div>"
str = str & "     </td>"
str = str & "     </tr>"
str = str & "     <tr> "
str = str & "       <td class='w-thir-f-p'>"
str = str & "        <div class='title'><strong>Father&#39;s Name</strong></div>"
str = str & "       </td>"
str = str & "   <td class='w-fiv-p t-a-c'> <div class='title'><strong>:</strong></div></td><td class='w-six-p'> <div class='title'><strong> "&strFahterName&" </strong></div></td></tr><tr> <td class='w-thir-f-p'> <div class='title'><strong>Mother&#39;s Name</strong></div></td><td class='w-fiv-p t-a-c'> <div class='title'><strong>:</strong></div></td><td class='w-six-p'> <div class='title'><strong>"&strMotherName&" </strong></div></td></tr><tr> <td class='w-thir-f-p' valign='top'> <div class='title'><strong>Contact Address</strong></div></td><td class='w-fiv-p t-a-c' valign='top'> <div class='title'><strong>:</strong></div></td><td class='w-six-p'> <div class='title'><strong>"&strContactAddress&" </strong></div></td></tr></table> </td><td class='w-twen-six-p'> <div class='img-wrapper'>" & varImg & " </div><div class='sig-wrapper'>" & varSigImg & "</div></td></tr><tr> <td colspan='2' align='center'> <div class='title t-a-c'><strong>Subject: <u>Written Test for the post of Trainee Senior Officer</u></strong></div></td></tr>"
str = str & " <tr> <td colspan='2'> <div class='title'> <p style='font-size:14px;'>Dear Sir/Madam,</p><p><br>We refer to application for the post of Trainee Senior Officer in Shahjalal Islami Bank Limited.<br>In this regard, you are advised to appear for a written test as per following program: </p></div></td></tr></table> "

str = str & " <br><table class='middle-t' style='font-size:14px;' > <tr> <td class='w-twe-p'> <div class='title'><strong>Date</strong></div></td><td class='w-fiv-p t-a-c'> <div class='title'><strong>:</strong></div></td><td class='w-sev-fiv-p'> <div class='title'><strong>November 30, 2018 (Friday)</strong></div></td></tr><tr> <td class='w-twe-p'> <div class='title'><strong>Centre</strong></div></td><td class='w-fiv-p t-a-c'> <div class='title'><strong>:</strong></div></td><td class='w-sev-fiv-p'> <div class='title'><strong>Mirpur Girls' Ideal Laboratory Institute, Mirpur 10, Dhaka 1216 (nearby BRTA)</strong></div></td></tr><tr> <td class='w-twe-p'> <div class='title'><strong>Time</strong></div></td><td class='w-fiv-p t-a-c'> <div class='title'><strong>:</strong></div></td><td class='w-sev-fiv-p'> <div class='title'><strong>10.00 am. to 11.30 am.</strong></div></td></tr></table> " 

'str = str & " <br><table class='cont' style='font-size:14px;'> <tr> <td colspan='2'> <div class='title'><strong><u>Please Note: </u></strong></div></td></tr></tr><tr> <td> <ol> <li>You must report to the centre by 09:30 AM sharp along with the Admit Card.</li><li>You should bring with you only black ball point pen.</li><li>Applicant must use the same signature for application, attendance sheet and answer script.</li><li>You will neither be allowed to use any digital wrist-watch, calculator, mobile phone, organizer <p style='padding-left:5px;'>or any other electronic devices, nor any book/note paper in the examination hall. Otherwise you</p><p style='padding-left:5px;'>will be silently expelled.</p></li></ol> </td></tr></table> " 

str = str & "<br><table class='cont' style='font-size:14px;' width='90%' cellspacing='0' cellpadding='0'><tr><td colspan='2'><div class='title'><strong><u>Please Note: </u></strong></div></td></tr><tr><td width='3%' valign='top'>1.</td><td width='97%'>You must report to the centre by 09:30 AM sharp along with the Admit Card. </td></tr><tr><td width='3%' valign='top'>2.</td><td width='97%'>You should bring with you only black ball point pen.</td></tr><tr><td width='3%' valign='top'>3.</td><td width='97%'> Applicant must use the same signature for application, attendance sheet and answer script.</td></tr><tr><td width='3%' valign='top'>4.</td><td width='97%'>You will neither be allowed to use any digital wrist-watch, calculator, mobile phone, organizer <br>or any other electronic devices, nor any book/note paper in the examination hall. Otherwise you<br>will be silently expelled.</td></tr></table>"

str = str & "<table class='cont' style='font-size:14px;'> <tr> <td> <p>Moreover, Bank will not bear any cost (i.e. travel, hotel etc.) for attending the aforesaid Test.</p><div class='i-wrapper'><br> <img src='http://ers.bdjobs.com/applications/shahjalalbank/dev/images/signature.png'/> <div><strong>Deputy Managing Director</strong></div></div></td></tr></table> "

str = str & "<br><br><table class='top' style='font-size:14px;'> <tr> <td class='w-twen-six-p v-a-t'><strong class='b-t'>Corporate Head Office:</strong> </td><td class='w-sev-four-'> Shahjalal Islami Bank Tower, Plot#4, Block # CWN(C), Gulshan Avenue, Gulshan, Dhaka-1212, Bangladesh. Phone:+88 02 9845457 (Hunting), Email; <a href='mailto:sblho@sjiblbd.com'>sblho@sjiblbd.com</a>, Website: <a href='http://www.sjiblbd.com'>www.sjiblbd.com</a>, </td></tr></table></div>"
%>