<%
'response.Write("hellowwwwwwwwwwwwwwww"&arrEducationId(i))	
If arrEducationId(i) < 3 Then
'response.Write("hellowwwwwwwwwwwwwwww"&arrAcademicDist(i))
    If arrAcademicDist(i) = "1" Then
		ssc_hsc_dist_name = "Brahmanbaria"
	ElseIf arrAcademicDist(i) = "2" Then
		ssc_hsc_dist_name = "Bagerhat"
	ElseIf arrAcademicDist(i) = "3" Then
		ssc_hsc_dist_name = "Bandarban"
	ElseIf arrAcademicDist(i) = "4" Then
		ssc_hsc_dist_name = "Barishal"
	ElseIf arrAcademicDist(i) = "5" Then
		ssc_hsc_dist_name = "Bhola"
	ElseIf arrAcademicDist(i) = "6" Then
		ssc_hsc_dist_name = "Bogura"
	ElseIf arrAcademicDist(i) = "7" Then
		ssc_hsc_dist_name = "Borguna"
	ElseIf arrAcademicDist(i) = "8" Then
		ssc_hsc_dist_name = "Chandpur"
	ElseIf arrAcademicDist(i) = "9" Then
		ssc_hsc_dist_name = "Chapainawabganj"
	ElseIf arrAcademicDist(i) = "10" Then
		ssc_hsc_dist_name = "Chattogram"
	ElseIf arrAcademicDist(i) = "11" Then
		ssc_hsc_dist_name = "Chuadanga"
	ElseIf arrAcademicDist(i) = "12" Then
		ssc_hsc_dist_name = "Cumilla"
	ElseIf arrAcademicDist(i) = "13" Then
		ssc_hsc_dist_name = "Cox's Bazar"
	ElseIf arrAcademicDist(i) = "14" Then
		ssc_hsc_dist_name = "Dhaka"
	ElseIf arrAcademicDist(i) = "15" Then
		ssc_hsc_dist_name = "Dinajpur"
	ElseIf arrAcademicDist(i) = "16" Then
		ssc_hsc_dist_name = "Faridpur"
	ElseIf arrAcademicDist(i) = "17" Then
		ssc_hsc_dist_name = "Feni"
	ElseIf arrAcademicDist(i) = "18" Then
		ssc_hsc_dist_name = "Gaibandha"
	ElseIf arrAcademicDist(i) = "19" Then
		ssc_hsc_dist_name = "Gazipur"
	ElseIf arrAcademicDist(i) = "20" Then
		ssc_hsc_dist_name = "Gopalgonj"
	ElseIf arrAcademicDist(i) = "21" Then
		ssc_hsc_dist_name = "Hobigonj"
	ElseIf arrAcademicDist(i) = "22" Then
		ssc_hsc_dist_name = "Jamalpur"
	ElseIf arrAcademicDist(i) = "23" Then
		ssc_hsc_dist_name = "Jashore"
	ElseIf arrAcademicDist(i) = "24" Then
		ssc_hsc_dist_name = "Jhalokathi"
	ElseIf arrAcademicDist(i) = "25" Then
		ssc_hsc_dist_name = "Jhenaidah"
	ElseIf arrAcademicDist(i) = "26" Then
		ssc_hsc_dist_name = "Joypurhat"
	ElseIf arrAcademicDist(i) = "27" Then
		ssc_hsc_dist_name = "Khagrachari"
	ElseIf arrAcademicDist(i) = "28" Then
		ssc_hsc_dist_name = "Khulna"
	ElseIf arrAcademicDist(i) = "29" Then
		ssc_hsc_dist_name = "Kishorgonj"
	ElseIf arrAcademicDist(i) = "30" Then
		ssc_hsc_dist_name = "Kurigram"
	ElseIf arrAcademicDist(i) = "31" Then
		ssc_hsc_dist_name = "Kushtia"
	ElseIf arrAcademicDist(i) = "32" Then
		ssc_hsc_dist_name = "Lalmonirhat"
	ElseIf arrAcademicDist(i) = "33" Then
		ssc_hsc_dist_name = "Laxmipur"
	ElseIf arrAcademicDist(i) = "34" Then
		ssc_hsc_dist_name = "Madaripur"
	ElseIf arrAcademicDist(i) = "35" Then
		ssc_hsc_dist_name = "Magura"
	ElseIf arrAcademicDist(i) = "36" Then
		ssc_hsc_dist_name = "Manikgonj"
	ElseIf arrAcademicDist(i) = "37" Then
		ssc_hsc_dist_name = "Meherpur"
	ElseIf arrAcademicDist(i) = "38" Then
		ssc_hsc_dist_name = "MoulaviBazar"
	ElseIf arrAcademicDist(i) = "39" Then
		ssc_hsc_dist_name = "Munshigonj"
	ElseIf arrAcademicDist(i) = "40" Then
		ssc_hsc_dist_name = "Mymensingh"
	ElseIf arrAcademicDist(i) = "41" Then
		ssc_hsc_dist_name = "Naogaon"
	ElseIf arrAcademicDist(i) = "42" Then
		ssc_hsc_dist_name = "Narail"
	ElseIf arrAcademicDist(i) = "43" Then
		ssc_hsc_dist_name = "Narayangonj"
	ElseIf arrAcademicDist(i) = "44" Then
		ssc_hsc_dist_name = "Narshingdi"
	ElseIf arrAcademicDist(i) = "45" Then
		ssc_hsc_dist_name = "Natore"
	ElseIf arrAcademicDist(i) = "46" Then
		ssc_hsc_dist_name = "Netrokona"
	ElseIf arrAcademicDist(i) = "47" Then
		ssc_hsc_dist_name = "Nilphamari"
	ElseIf arrAcademicDist(i) = "48" Then
		ssc_hsc_dist_name = "Noakhali"
	ElseIf arrAcademicDist(i) = "49" Then
		ssc_hsc_dist_name = "Pabna"
	ElseIf arrAcademicDist(i) = "50" Then
		ssc_hsc_dist_name = "Panchagahr"
	ElseIf arrAcademicDist(i) = "51" Then
		ssc_hsc_dist_name = "Patuakhali"
	ElseIf arrAcademicDist(i) = "52" Then
		ssc_hsc_dist_name = "Pirojpur"
	ElseIf arrAcademicDist(i) = "53" Then
		ssc_hsc_dist_name = "Rajbari"
	ElseIf arrAcademicDist(i) = "54" Then
		ssc_hsc_dist_name = "Rajshahi"
	ElseIf arrAcademicDist(i) = "55" Then
		ssc_hsc_dist_name = "Rangamati"
	ElseIf arrAcademicDist(i) = "56" Then
		ssc_hsc_dist_name = "Rangpur"
	ElseIf arrAcademicDist(i) = "57" Then
		ssc_hsc_dist_name = "Satkhira"
	ElseIf arrAcademicDist(i) = "58" Then
		ssc_hsc_dist_name = "Shariatpur"
	ElseIf arrAcademicDist(i) = "59" Then
		ssc_hsc_dist_name = "Sherpur"
	ElseIf arrAcademicDist(i) = "60" Then
		ssc_hsc_dist_name = "Sirajgonj"
	ElseIf arrAcademicDist(i) = "61" Then
		ssc_hsc_dist_name = "Sunamgonj"
	ElseIf arrAcademicDist(i) = "62" Then
		ssc_hsc_dist_name = "Sylhet"
	ElseIf arrAcademicDist(i) = "63" Then
		ssc_hsc_dist_name = "Tangail"
	ElseIf arrAcademicDist(i) = "64" Then
		ssc_hsc_dist_name = "Thakurgaon"
	End If

End If

'If arrEducationId(i) = 2 Then
'	
'    If strAcademicDist_hsc = "1" Then
'		strAcademicDist_hscName = "Brahmanbaria"
'	ElseIf strAcademicDist_hsc = "2" Then
'		strAcademicDist_hscName = "Bagerhat"
'	ElseIf strAcademicDist_hsc = "3" Then
'		strAcademicDist_hscName = "Bandarban"
'	ElseIf strAcademicDist_hsc = "4" Then
'		strAcademicDist_hscName = "Barisal"
'	ElseIf strAcademicDist_hsc = "5" Then
'		strAcademicDist_hscName = "Bhola"
'	ElseIf strAcademicDist_hsc = "6" Then
'		strAcademicDist_hscName = "Bogra"
'	ElseIf strAcademicDist_hsc = "7" Then
'		strAcademicDist_hscName = "Borguna"
'	ElseIf strAcademicDist_hsc = "8" Then
'		strAcademicDist_hscName = "Chandpur"
'	ElseIf strAcademicDist_hsc = "9" Then
'		strAcademicDist_hscName = "Chapainawabganj"
'	ElseIf strAcademicDist_hsc = "10" Then
'		strAcademicDist_hscName = "Chattogram"
'	ElseIf strAcademicDist_hsc = "11" Then
'		strAcademicDist_hscName = "Chuadanga"
'	ElseIf strAcademicDist_hsc = "12" Then
'		strAcademicDist_hscName = "Cumilla"
'	ElseIf strAcademicDist_hsc = "13" Then
'		strAcademicDist_hscName = "Cox's Bazar"
'	ElseIf strAcademicDist_hsc = "14" Then
'		strAcademicDist_hscName = "Dhaka"
'	ElseIf strAcademicDist_hsc = "15" Then
'		strAcademicDist_hscName = "Dinajpur"
'	ElseIf strAcademicDist_hsc = "16" Then
'		strAcademicDist_hscName = "Faridpur"
'	ElseIf strAcademicDist_hsc = "17" Then
'		strAcademicDist_hscName = "Feni"
'	ElseIf strAcademicDist_hsc = "18" Then
'		strAcademicDist_hscName = "Gaibandha"
'	ElseIf strAcademicDist_hsc = "19" Then
'		strAcademicDist_hscName = "Gazipur"
'	ElseIf strAcademicDist_hsc = "20" Then
'		strAcademicDist_hscName = "Gopalgonj"
'	ElseIf strAcademicDist_hsc = "21" Then
'		strAcademicDist_hscName = "Hobigonj"
'	ElseIf strAcademicDist_hsc = "22" Then
'		strAcademicDist_hscName = "Jamalpur"
'	ElseIf strAcademicDist_hsc = "23" Then
'		strAcademicDist_hscName = "Jessore"
'	ElseIf strAcademicDist_hsc = "24" Then
'		strAcademicDist_hscName = "Jhalokathi"
'	ElseIf strAcademicDist_hsc = "25" Then
'		strAcademicDist_hscName = "Jhenaidah"
'	ElseIf strAcademicDist_hsc = "26" Then
'		strAcademicDist_hscName = "Joypurhat"
'	ElseIf strAcademicDist_hsc = "27" Then
'		strAcademicDist_hscName = "Khagrachari"
'	ElseIf strAcademicDist_hsc = "28" Then
'		strAcademicDist_hscName = "Khulna"
'	ElseIf strAcademicDist_hsc = "29" Then
'		strAcademicDist_hscName = "Kishorgonj"
'	ElseIf strAcademicDist_hsc = "30" Then
'		strAcademicDist_hscName = "Kurigram"
'	ElseIf strAcademicDist_hsc = "31" Then
'		strAcademicDist_hscName = "Kushtia"
'	ElseIf strAcademicDist_hsc = "32" Then
'		strAcademicDist_hscName = "Lalmonirhat"
'	ElseIf strAcademicDist_hsc = "33" Then
'		strAcademicDist_hscName = "Laxmipur"
'	ElseIf strAcademicDist_hsc = "34" Then
'		strAcademicDist_hscName = "Madaripur"
'	ElseIf strAcademicDist_hsc = "35" Then
'		strAcademicDist_hscName = "Magura"
'	ElseIf strAcademicDist_hsc = "36" Then
'		strAcademicDist_hscName = "Manikgonj"
'	ElseIf strAcademicDist_hsc = "37" Then
'		strAcademicDist_hscName = "Meherpur"
'	ElseIf strAcademicDist_hsc = "38" Then
'		strAcademicDist_hscName = "MoulaviBazar"
'	ElseIf strAcademicDist_hsc = "39" Then
'		strAcademicDist_hscName = "Munshigonj"
'	ElseIf strAcademicDist_hsc = "40" Then
'		strAcademicDist_hscName = "Mymensingh"
'	ElseIf strAcademicDist_hsc = "41" Then
'		strAcademicDist_hscName = "Naogaon"
'	ElseIf strAcademicDist_hsc = "42" Then
'		strAcademicDist_hscName = "Narail"
'	ElseIf strAcademicDist_hsc = "43" Then
'		strAcademicDist_hscName = "Narayangonj"
'	ElseIf strAcademicDist_hsc = "44" Then
'		strAcademicDist_hscName = "Narshingdi"
'	ElseIf strAcademicDist_hsc = "45" Then
'		strAcademicDist_hscName = "Natore"
'	ElseIf strAcademicDist_hsc = "46" Then
'		strAcademicDist_hscName = "Netrokona"
'	ElseIf strAcademicDist_hsc = "47" Then
'		strAcademicDist_hscName = "Nilphamari"
'	ElseIf strAcademicDist_hsc = "48" Then
'		strAcademicDist_hscName = "Noakhali"
'	ElseIf strAcademicDist_hsc = "49" Then
'		strAcademicDist_hscName = "Pabna"
'	ElseIf strAcademicDist_hsc = "50" Then
'		strAcademicDist_hscName = "Panchagahr"
'	ElseIf strAcademicDist_hsc = "51" Then
'		strAcademicDist_hscName = "Patuakhali"
'	ElseIf strAcademicDist_hsc = "52" Then
'		strAcademicDist_hscName = "Pirojpur"
'	ElseIf strAcademicDist_hsc = "53" Then
'		strAcademicDist_hscName = "Rajbari"
'	ElseIf strAcademicDist_hsc = "54" Then
'		strAcademicDist_hscName = "Rajshahi"
'	ElseIf strAcademicDist_hsc = "55" Then
'		strAcademicDist_hscName = "Rangamati"
'	ElseIf strAcademicDist_hsc = "56" Then
'		strAcademicDist_hscName = "Rangpur"
'	ElseIf strAcademicDist_hsc = "57" Then
'		strAcademicDist_hscName = "Satkhira"
'	ElseIf strAcademicDist_hsc = "58" Then
'		strAcademicDist_hscName = "Shariatpur"
'	ElseIf strAcademicDist_hsc = "59" Then
'		strAcademicDist_hscName = "Sherpur"
'	ElseIf strAcademicDist_hsc = "60" Then
'		strAcademicDist_hscName = "Sirajgonj"
'	ElseIf strAcademicDist_hsc = "61" Then
'		strAcademicDist_hscName = "Sunamgonj"
'	ElseIf strAcademicDist_hsc = "62" Then
'		strAcademicDist_hscName = "Sylhet"
'	ElseIf strAcademicDist_hsc = "63" Then
'		strAcademicDist_hscName = "Tangail"
'	ElseIf strAcademicDist_hsc = "64" Then
'		strAcademicDist_hscName = "Thakurgaon"
'	End If	
'	
'End If
%>
