<%
'response.Write("hellowwwwwwwwwwwwwwww"&bytEduLevel)	
If bytEduLevel < 3 Then
'response.Write("hellowwwwwwwwwwwwwwww"&strAcademicDist)
    If strAcademicDist = "1" Then
		ssc_hsc_dist_name = "Brahmanbaria"
	ElseIf strAcademicDist = "2" Then
		ssc_hsc_dist_name = "Bagerhat"
	ElseIf strAcademicDist = "3" Then
		ssc_hsc_dist_name = "Bandarban"
	ElseIf strAcademicDist = "4" Then
		ssc_hsc_dist_name = "Barishal"
	ElseIf strAcademicDist = "5" Then
		ssc_hsc_dist_name = "Bhola"
	ElseIf strAcademicDist = "6" Then
		ssc_hsc_dist_name = "Bogura"
	ElseIf strAcademicDist = "7" Then
		ssc_hsc_dist_name = "Borguna"
	ElseIf strAcademicDist = "8" Then
		ssc_hsc_dist_name = "Chandpur"
	ElseIf strAcademicDist = "9" Then
		ssc_hsc_dist_name = "Chapainawabganj"
	ElseIf strAcademicDist = "10" Then
		ssc_hsc_dist_name = "Chattogram"
	ElseIf strAcademicDist = "11" Then
		ssc_hsc_dist_name = "Chuadanga"
	ElseIf strAcademicDist = "12" Then
		ssc_hsc_dist_name = "Cumilla"
	ElseIf strAcademicDist = "13" Then
		ssc_hsc_dist_name = "Cox's Bazar"
	ElseIf strAcademicDist = "14" Then
		ssc_hsc_dist_name = "Dhaka"
	ElseIf strAcademicDist = "15" Then
		ssc_hsc_dist_name = "Dinajpur"
	ElseIf strAcademicDist = "16" Then
		ssc_hsc_dist_name = "Faridpur"
	ElseIf strAcademicDist = "17" Then
		ssc_hsc_dist_name = "Feni"
	ElseIf strAcademicDist = "18" Then
		ssc_hsc_dist_name = "Gaibandha"
	ElseIf strAcademicDist = "19" Then
		ssc_hsc_dist_name = "Gazipur"
	ElseIf strAcademicDist = "20" Then
		ssc_hsc_dist_name = "Gopalgonj"
	ElseIf strAcademicDist = "21" Then
		ssc_hsc_dist_name = "Hobigonj"
	ElseIf strAcademicDist = "22" Then
		ssc_hsc_dist_name = "Jamalpur"
	ElseIf strAcademicDist = "23" Then
		ssc_hsc_dist_name = "Jashore"
	ElseIf strAcademicDist = "24" Then
		ssc_hsc_dist_name = "Jhalokathi"
	ElseIf strAcademicDist = "25" Then
		ssc_hsc_dist_name = "Jhenaidah"
	ElseIf strAcademicDist = "26" Then
		ssc_hsc_dist_name = "Joypurhat"
	ElseIf strAcademicDist = "27" Then
		ssc_hsc_dist_name = "Khagrachari"
	ElseIf strAcademicDist = "28" Then
		ssc_hsc_dist_name = "Khulna"
	ElseIf strAcademicDist = "29" Then
		ssc_hsc_dist_name = "Kishorgonj"
	ElseIf strAcademicDist = "30" Then
		ssc_hsc_dist_name = "Kurigram"
	ElseIf strAcademicDist = "31" Then
		ssc_hsc_dist_name = "Kushtia"
	ElseIf strAcademicDist = "32" Then
		ssc_hsc_dist_name = "Lalmonirhat"
	ElseIf strAcademicDist = "33" Then
		ssc_hsc_dist_name = "Laxmipur"
	ElseIf strAcademicDist = "34" Then
		ssc_hsc_dist_name = "Madaripur"
	ElseIf strAcademicDist = "35" Then
		ssc_hsc_dist_name = "Magura"
	ElseIf strAcademicDist = "36" Then
		ssc_hsc_dist_name = "Manikgonj"
	ElseIf strAcademicDist = "37" Then
		ssc_hsc_dist_name = "Meherpur"
	ElseIf strAcademicDist = "38" Then
		ssc_hsc_dist_name = "MoulaviBazar"
	ElseIf strAcademicDist = "39" Then
		ssc_hsc_dist_name = "Munshigonj"
	ElseIf strAcademicDist = "40" Then
		ssc_hsc_dist_name = "Mymensingh"
	ElseIf strAcademicDist = "41" Then
		ssc_hsc_dist_name = "Naogaon"
	ElseIf strAcademicDist = "42" Then
		ssc_hsc_dist_name = "Narail"
	ElseIf strAcademicDist = "43" Then
		ssc_hsc_dist_name = "Narayangonj"
	ElseIf strAcademicDist = "44" Then
		ssc_hsc_dist_name = "Narshingdi"
	ElseIf strAcademicDist = "45" Then
		ssc_hsc_dist_name = "Natore"
	ElseIf strAcademicDist = "46" Then
		ssc_hsc_dist_name = "Netrokona"
	ElseIf strAcademicDist = "47" Then
		ssc_hsc_dist_name = "Nilphamari"
	ElseIf strAcademicDist = "48" Then
		ssc_hsc_dist_name = "Noakhali"
	ElseIf strAcademicDist = "49" Then
		ssc_hsc_dist_name = "Pabna"
	ElseIf strAcademicDist = "50" Then
		ssc_hsc_dist_name = "Panchagahr"
	ElseIf strAcademicDist = "51" Then
		ssc_hsc_dist_name = "Patuakhali"
	ElseIf strAcademicDist = "52" Then
		ssc_hsc_dist_name = "Pirojpur"
	ElseIf strAcademicDist = "53" Then
		ssc_hsc_dist_name = "Rajbari"
	ElseIf strAcademicDist = "54" Then
		ssc_hsc_dist_name = "Rajshahi"
	ElseIf strAcademicDist = "55" Then
		ssc_hsc_dist_name = "Rangamati"
	ElseIf strAcademicDist = "56" Then
		ssc_hsc_dist_name = "Rangpur"
	ElseIf strAcademicDist = "57" Then
		ssc_hsc_dist_name = "Satkhira"
	ElseIf strAcademicDist = "58" Then
		ssc_hsc_dist_name = "Shariatpur"
	ElseIf strAcademicDist = "59" Then
		ssc_hsc_dist_name = "Sherpur"
	ElseIf strAcademicDist = "60" Then
		ssc_hsc_dist_name = "Sirajgonj"
	ElseIf strAcademicDist = "61" Then
		ssc_hsc_dist_name = "Sunamgonj"
	ElseIf strAcademicDist = "62" Then
		ssc_hsc_dist_name = "Sylhet"
	ElseIf strAcademicDist = "63" Then
		ssc_hsc_dist_name = "Tangail"
	ElseIf strAcademicDist = "64" Then
		ssc_hsc_dist_name = "Thakurgaon"
	End If

End If

%>
