<%
If strHomeDistrict = "1" Then
				dist = "B. Baria"
			ElseIf strHomeDistrict = "2" Then
				dist = "Bagerhat"
			ElseIf strHomeDistrict = "3" Then
				dist = "Bandarban"
			ElseIf strHomeDistrict = "4" Then
				dist = "Barisal"
			ElseIf strHomeDistrict = "5" Then
				dist = "Bhola"
			ElseIf strHomeDistrict = "6" Then
				dist = "Bogra"
			ElseIf strHomeDistrict = "7" Then
				dist = "Borguna"
			ElseIf strHomeDistrict = "8" Then
				dist = "Chandpur"
			ElseIf strHomeDistrict = "9" Then
				dist = "Chapainawabganj"
			ElseIf strHomeDistrict = "10" Then
				dist = "Chittagong"
			ElseIf strHomeDistrict = "11" Then
				dist = "Chuadanga"
			ElseIf strHomeDistrict = "12" Then
				dist = "Comilla"
			ElseIf strHomeDistrict = "13" Then
				dist = "Cox's Bazar"
			ElseIf strHomeDistrict = "14" Then
				dist = "Dhaka"
			ElseIf strHomeDistrict = "15" Then
				dist = "Dinajpur"
			ElseIf strHomeDistrict = "16" Then
				dist = "Faridpur"
			ElseIf strHomeDistrict = "17" Then
				dist = "Feni"
			ElseIf strHomeDistrict = "18" Then
				dist = "Gaibandha"
			ElseIf strHomeDistrict = "19" Then
				dist = "Gazipur"
			ElseIf strHomeDistrict = "20" Then
				dist = "Gopalgonj"
			ElseIf strHomeDistrict = "21" Then
				dist = "Hobigonj"
			ElseIf strHomeDistrict = "22" Then
				dist = "Jamalpur"
			ElseIf strHomeDistrict = "23" Then
				dist = "Jessore"
			ElseIf strHomeDistrict = "24" Then
				dist = "Jhalokathi"
			ElseIf strHomeDistrict = "25" Then
				dist = "Jhenaidah"
			ElseIf strHomeDistrict = "26" Then
				dist = "Joypurhat"
			ElseIf strHomeDistrict = "27" Then
				dist = "Khagrachari"
			ElseIf strHomeDistrict = "28" Then
				dist = "Khulna"
			ElseIf strHomeDistrict = "29" Then
				dist = "Kishorgonj"
			ElseIf strHomeDistrict = "30" Then
				dist = "Kurigram"
			ElseIf strHomeDistrict = "31" Then
				dist = "Kushtia"
			ElseIf strHomeDistrict = "32" Then
				dist = "Lalmonirhat"
			ElseIf strHomeDistrict = "33" Then
				dist = "Laxmipur"
			ElseIf strHomeDistrict = "34" Then
				dist = "Madaripur"
			ElseIf strHomeDistrict = "35" Then
				dist = "Magura"
			ElseIf strHomeDistrict = "36" Then
				dist = "Manikgonj"
			ElseIf strHomeDistrict = "37" Then
				dist = "Meherpur"
			ElseIf strHomeDistrict = "38" Then
				dist = "MoulaviBazar"
			ElseIf strHomeDistrict = "39" Then
				dist = "Munshigonj"
			ElseIf strHomeDistrict = "40" Then
				dist = "Mymensingh"
			ElseIf strHomeDistrict = "41" Then
				dist = "Naogaon"
			ElseIf strHomeDistrict = "42" Then
				dist = "Narail"
			ElseIf strHomeDistrict = "43" Then
				dist = "Narayangonj"
			ElseIf strHomeDistrict = "44" Then
				dist = "Narshingdi"
			ElseIf strHomeDistrict = "45" Then
				dist = "Natore"
			ElseIf strHomeDistrict = "46" Then
				dist = "Netrokona"
			ElseIf strHomeDistrict = "47" Then
				dist = "Nilphamari"
			ElseIf strHomeDistrict = "48" Then
				dist = "Noakhali"
			ElseIf strHomeDistrict = "49" Then
				dist = "Pabna"
			ElseIf strHomeDistrict = "50" Then
				dist = "Panchagahr"
			ElseIf strHomeDistrict = "51" Then
				dist = "Patuakhali"
			ElseIf strHomeDistrict = "52" Then
				dist = "Pirojpur"
			ElseIf strHomeDistrict = "53" Then
				dist = "Rajbari"
			ElseIf strHomeDistrict = "54" Then
				dist = "Rajshahi"
			ElseIf strHomeDistrict = "55" Then
				dist = "Rangamati"
			ElseIf strHomeDistrict = "56" Then
				dist = "Rangpur"
			ElseIf strHomeDistrict = "57" Then
				dist = "Satkhira"
			ElseIf strHomeDistrict = "58" Then
				dist = "Shariatpur"
			ElseIf strHomeDistrict = "59" Then
				dist = "Sherpur"
			ElseIf strHomeDistrict = "60" Then
				dist = "Sirajgonj"
			ElseIf strHomeDistrict = "61" Then
				dist = "Sunamgonj"
			ElseIf strHomeDistrict = "62" Then
				dist = "Sylhet"
			ElseIf strHomeDistrict = "63" Then
				dist = "Tangail"
			ElseIf strHomeDistrict = "64" Then
				dist = "Thakurgaon"
			End If	

			If strHomeDistrict2 = "1" Then
				dist2 = "B. Baria"
			ElseIf strHomeDistrict2 = "2" Then
				dist2 = "Bagerhat"
			ElseIf strHomeDistrict2 = "3" Then
				dist2 = "Bandarban"
			ElseIf strHomeDistrict2 = "4" Then
				dist2 = "Barisal"
			ElseIf strHomeDistrict2 = "5" Then
				dist2 = "Bhola"
			ElseIf strHomeDistrict2 = "6" Then
				dist2 = "Bogra"
			ElseIf strHomeDistrict2 = "7" Then
				dist2 = "Borguna"
			ElseIf strHomeDistrict2 = "8" Then
				dist2 = "Chandpur"
			ElseIf strHomeDistrict2 = "9" Then
				dist2 = "Chapainawabganj"
			ElseIf strHomeDistrict2 = "10" Then
				dist2 = "Chittagong"
			ElseIf strHomeDistrict2 = "11" Then
				dist2 = "Chuadanga"
			ElseIf strHomeDistrict2 = "12" Then
				dist2 = "Comilla"
			ElseIf strHomeDistrict2 = "13" Then
				dist2 = "Cox's Bazar"
			ElseIf strHomeDistrict2 = "14" Then
				dist2 = "Dhaka"
			ElseIf strHomeDistrict2 = "15" Then
				dist2 = "Dinajpur"
			ElseIf strHomeDistrict2 = "16" Then
				dist2 = "Faridpur"
			ElseIf strHomeDistrict2 = "17" Then
				dist2 = "Feni"
			ElseIf strHomeDistrict2 = "18" Then
				dist2 = "Gaibandha"
			ElseIf strHomeDistrict2 = "19" Then
				dist2 = "Gazipur"
			ElseIf strHomeDistrict2 = "20" Then
				dist2 = "Gopalgonj"
			ElseIf strHomeDistrict2 = "21" Then
				dist2 = "Hobigonj"
			ElseIf strHomeDistrict2 = "22" Then
				dist2 = "Jamalpur"
			ElseIf strHomeDistrict2 = "23" Then
				dist2 = "Jessore"
			ElseIf strHomeDistrict2 = "24" Then
				dist2 = "Jhalokathi"
			ElseIf strHomeDistrict2 = "25" Then
				dist2 = "Jhenaidah"
			ElseIf strHomeDistrict2 = "26" Then
				dist2 = "Joypurhat"
			ElseIf strHomeDistrict2 = "27" Then
				dist2 = "Khagrachari"
			ElseIf strHomeDistrict2 = "28" Then
				dist2 = "Khulna"
			ElseIf strHomeDistrict2 = "29" Then
				dist2 = "Kishorgonj"
			ElseIf strHomeDistrict2 = "30" Then
				dist2 = "Kurigram"
			ElseIf strHomeDistrict2 = "31" Then
				dist2 = "Kushtia"
			ElseIf strHomeDistrict2 = "32" Then
				dist2 = "Lalmonirhat"
			ElseIf strHomeDistrict2 = "33" Then
				dist2 = "Laxmipur"
			ElseIf strHomeDistrict2 = "34" Then
				dist2 = "Madaripur"
			ElseIf strHomeDistrict2 = "35" Then
				dist2 = "Magura"
			ElseIf strHomeDistrict2 = "36" Then
				dist2 = "Manikgonj"
			ElseIf strHomeDistrict2 = "37" Then
				dist2 = "Meherpur"
			ElseIf strHomeDistrict2 = "38" Then
				dist2 = "MoulaviBazar"
			ElseIf strHomeDistrict2 = "39" Then
				dist2 = "Munshigonj"
			ElseIf strHomeDistrict2 = "40" Then
				dist2 = "Mymensingh"
			ElseIf strHomeDistrict2 = "41" Then
				dist2 = "Naogaon"
			ElseIf strHomeDistrict2 = "42" Then
				dist2 = "Narail"
			ElseIf strHomeDistrict2 = "43" Then
				dist2 = "Narayangonj"
			ElseIf strHomeDistrict2 = "44" Then
				dist2 = "Narshingdi"
			ElseIf strHomeDistrict2 = "45" Then
				dist2 = "Natore"
			ElseIf strHomeDistrict2 = "46" Then
				dist2 = "Netrokona"
			ElseIf strHomeDistrict2 = "47" Then
				dist2 = "Nilphamari"
			ElseIf strHomeDistrict2 = "48" Then
				dist2 = "Noakhali"
			ElseIf strHomeDistrict2 = "49" Then
				dist2 = "Pabna"
			ElseIf strHomeDistrict2 = "50" Then
				dist2 = "Panchagahr"
			ElseIf strHomeDistrict2 = "51" Then
				dist2 = "Patuakhali"
			ElseIf strHomeDistrict2 = "52" Then
				dist2 = "Pirojpur"
			ElseIf strHomeDistrict2 = "53" Then
				dist2 = "Rajbari"
			ElseIf strHomeDistrict2 = "54" Then
				dist2 = "Rajshahi"
			ElseIf strHomeDistrict2 = "55" Then
				dist2 = "Rangamati"
			ElseIf strHomeDistrict2 = "56" Then
				dist2 = "Rangpur"
			ElseIf strHomeDistrict2 = "57" Then
				dist2 = "Satkhira"
			ElseIf strHomeDistrict2 = "58" Then
				dist2 = "Shariatpur"
			ElseIf strHomeDistrict2 = "59" Then
				dist2 = "Sherpur"
			ElseIf strHomeDistrict2 = "60" Then
				dist2 = "Sirajgonj"
			ElseIf strHomeDistrict2 = "61" Then
				dist2 = "Sunamgonj"
			ElseIf strHomeDistrict2 = "62" Then
				dist2 = "Sylhet"
			ElseIf strHomeDistrict2 = "63" Then
				dist2 = "Tangail"
			ElseIf strHomeDistrict2 = "64" Then
				dist2 = "Thakurgaon"
			End If	
%>