<%
' some common array goes to utilty.asp> /applications/common/include_file 

 'arrDegreeNameGrad = Array("BA(Pass)","BSS(Pass)","BSc(Pass)","BBS(Pass)","BCom(Pass)","B.Ed(Pass)","LLB(Pass)","Fazil","BBA","BA(Hons)","BBS(Hons)","BCom(Hons)","BSc(Hons)","BSc(Engg)","BSS(Hons)","B.Ed(Hons)","LLB(Hons)")



arrDegreeNameGrad = Array("BA(Pass)","BSS(Pass)","BSc(Pass)","BBS(Pass)","BCom(Pass)","B.Ed(Pass)","LLB(Pass)","Fazil","BBA","BA(Hons)","BBS(Hons)","BCom(Hons)","BSc(Hons)","BSc(Engg)","BSS(Hons)","B.Ed(Hons)","LLB(Hons)","L.L.B.(Hons)")
	 
arrDegreeNamePostGrad = Array("MA","MS","MSc","MSS","MCom","MBS","MBA","MBM","M.Ed","MSc(Engg)","L.L.M.","Kamil") 


'arrSubjectGrad = Array("Accounting","Accounting & Information System","Agriculture","Agro-technology","Animal Husbandry","Anthropology","Applied Chemistry","Applied Mathematics","Applied Physics","Arabic","Archaeology","Architecture","Arts","Automobile","Banking", "Bengali","Biochemistry","Biology","Biotechnology","Botany","Brand Management","Business Administration","Business Studies","Chemical Engineering","Chemistry","Civil Engineering","Commerce","Communication Engineering","Computer Applications","Computer Engineering","Computer Science","Computer Science & Engineering","Computing & Information System","Cost & Management Accounting","Cost Accounting","Development Studies","Economics","Education","Electrical & Electronic Engineering","Electronics","Electronics and Telecommunication Engineering","English","Environmental Planning","Environmental Science","Finance","Finance & Banking","Fine Arts","Fisheries","Flim and Media","Forestry","Genetics","Geography","Geography and Environment","Geology","Government & Politics","History","Horticulture","Hospitality Management","Hospitality Management","Human Resource Management","Industrial Eng & Production","Industrial Engineering","Industrial Management","Industrial Relations","Information Engineering","Information Science & Library Management","Information Systems","Information Technology","Insurance","International Business","International Relations","Islamic History & Culture","Islamic Studies","Journalism","Language","Law","Linguistics","Management","Management Information System","Management Studies/Science","Marine Engineering","Marketing","Mass Communication & Journalism","Materials & Metallurgical Engineering","Mathematics","Mechanical Engineering","Medicine","Microbiology","Nautical Science","Naval Architecture and Marine Engineering","Personnel Management","Petroleum and Mineral Resource Engineering","Pharmaceutical Technology","Pharmacology","Pharmacy","Philosophy","Physics","Political Science","Population Science","Psychology","Public Administration","Public Health","Public Relations","Sanskrit & Pali","Science","Service Marketing","Social Science","Social Work","Sociology","Statistics","Strategic Management","Supply Chain Management","Telecommunication","Textile Technology","Theater & Music","Urban & Regional Planning","Urdu & Persian","Veterinary Science","Water Resources Engineering","Women Studies","World Religions","Zoology","Others")

'arrSubjectPostGrad = Array("Accounting","Accounting & Information System","Agriculture","Agro-technology","Animal Husbandry","Anthropology","Applied Chemistry","Applied Mathematics","Applied Physics","Arabic","Archaeology","Architecture","Arts","Automobile","Banking", "Bengali","Biochemistry","Biology","Biotechnology","Botany","Brand Management","Business Administration","Business Studies","Chemical Engineering","Chemistry","Civil Engineering","Commerce","Communication Engineering","Computer Applications","Computer Engineering","Computer Science","Computer Science & Engineering","Computing & Information System","Cost & Management Accounting","Cost Accounting","Development Studies","Economics","Education","Electrical & Electronic Engineering","Electronics","Electronics and Telecommunication Engineering","English","Environmental Planning","Environmental Science","Finance","Finance & Banking","Fine Arts","Fisheries","Flim and Media","Forestry","Genetics","Geography","Geography and Environment","Geology","Government & Politics","History","Horticulture","Hospitality Management","Hospitality Management","Human Resource Management","Industrial Eng & Production","Industrial Engineering","Industrial Management","Industrial Relations","Information Engineering","Information Science & Library Management","Information Systems","Information Technology","Insurance","International Business","International Relations","Islamic History & Culture","Islamic Studies","Journalism","Language","Law","Linguistics","Management","Management Information System","Management Studies/Science","Marine Engineering","Marketing","Mass Communication & Journalism","Materials & Metallurgical Engineering","Mathematics","Mechanical Engineering","Medicine","Microbiology","Nautical Science","Naval Architecture and Marine Engineering","Personnel Management","Petroleum and Mineral Resource Engineering","Pharmaceutical Technology","Pharmacology","Pharmacy","Philosophy","Physics","Political Science","Population Science","Psychology","Public Administration","Public Health","Public Relations","Sanskrit & Pali","Science","Service Marketing","Social Science","Social Work","Sociology","Statistics","Strategic Management","Supply Chain Management","Telecommunication","Textile Technology","Theater & Music","Urban & Regional Planning","Urdu & Persian","Veterinary Science","Water Resources Engineering","Women Studies","World Religions","Zoology","Others")



%>