<%
	intRefID = Trim(Request.Form("hidReferenceId1"))
	strReferenceName1 = Trim(Request.Form("txtReferenceName1"))
	strReferenceName1 = GiveReplacedString(strReferenceName1)
	strReferencePosition1 = Trim(Request.Form("txtReferencePosition1"))
	strReferencePosition1 = GiveReplacedString(strReferencePosition1)
	strReferenceAddress1 = Trim(Request.Form("txtReferenceAddress1")) 
	strReferenceAddress1 = GiveReplacedString(strReferenceAddress1)
	strReferencePhone1 = Trim(Request.Form("txtReferencePhone1")) 
	strReferencePhone1 = GiveReplacedString(strReferencePhone1)
	'strRefCell = Trim(Request.Form("txtReferenceCellPhone1")) 
	strReferenceEmail1 = Trim(Request.Form("txtReferenceEmail1")) 
	strReferenceEmail1 = GiveReplacedString(strReferenceEmail1)
	
	intRefID2 = Request.Form("hidReferenceId2")
	strReferenceName2 = Trim(Request.Form("txtReferenceName2"))
	strReferenceName2 = GiveReplacedString(strReferenceName2)
	strReferencePosition2 = Trim(Request.Form("txtReferencePosition2"))
	strReferencePosition2 = GiveReplacedString(strReferencePosition2)
	strReferenceAddress2 = Trim(Request.Form("txtReferenceAddress2")) 
	strReferenceAddress2 = GiveReplacedString(strReferenceAddress2)
	strReferencePhone2 = Trim(Request.Form("txtReferencePhone2")) 
	strReferencePhone2 = GiveReplacedString(strReferencePhone2)
	'strRefCell = Trim(Request.Form("txtReferenceCellPhone1")) 
	strReferenceEmail2 = Trim(Request.Form("txtReferenceEmail2")) 
	strReferenceEmail2 = GiveReplacedString(strReferenceEmail2)
%>